-- SQL Setup for FateAutomata Kiosk Supabase Database
-- Run these in your Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- =====================================================================
-- OPTION A: IF YOU DO NOT HAVE THE 'attendance' TABLE YET
-- =====================================================================
-- Create the attendance table from scratch:
-- CREATE TABLE IF NOT EXISTS public.attendance (
--     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     student_name TEXT NOT NULL,
--     timestamp TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
--     synced BOOLEAN DEFAULT FALSE,
--     lanyard_compliant BOOLEAN DEFAULT TRUE,
--     dresscode_compliant BOOLEAN DEFAULT TRUE
-- );


-- =====================================================================
-- OPTION B: IF YOU ALREADY HAVE THE 'attendance' TABLE (MIGRATION)
-- =====================================================================
-- Run this to add the required compliance columns to your existing table:
ALTER TABLE public.attendance 
ADD COLUMN IF NOT EXISTS synced BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lanyard_compliant BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS dresscode_compliant BOOLEAN DEFAULT TRUE;


-- =====================================================================
-- 2. SETUP THE METRICS TABLE (REQUIRED FOR RASPBERRY PI TELEMETRY)
-- =====================================================================
-- If you already have a metrics table and do not need its old data, 
-- uncomment the line below to delete (drop) the old table first:
-- DROP TABLE IF EXISTS public.metrics;

CREATE TABLE IF NOT EXISTS public.metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    face_extract_ms NUMERIC,
    lanyard_ms NUMERIC,
    dress_ms NUMERIC,
    end_to_end_ms NUMERIC,
    cpu_percent NUMERIC,
    ram_percent NUMERIC,
    temp_c NUMERIC,
    raw_dress_detected NUMERIC,
    smoothed_dress_detected NUMERIC
);
